apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

configMapGenerator:
  - name: grafana-postgres-dashboard
    files:
      - postgres-dashboard.json


resources:
  - configmap.yaml
  - dashboard-configmap.yaml
  - deployment.yaml

generatorOptions:
  disableNameSuffixHash: true
