{
 "title": "PostgreSQL Exporter - Basic",
 "tags": [
  "postgres",
  "exporter",
  "prometheus"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "PostgreSQL - Connections",
   "type": "graph",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    { "expr": "pg_stat_database_numbackends", "legendFormat": "{{datname}}" }
   ]
  },
  {
   "title": "PostgreSQL - Transactions",
   "type": "graph",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[1m])",
     "legendFormat": "Commits - {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback[1m])",
     "legendFormat": "Rollbacks - {{datname}}"
    }
   ]
  },
  {
   "title": "PostgreSQL - Tuples Fetched/Returned",
   "type": "graph",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_returned[1m])",
     "legendFormat": "Returned - {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched[1m])",
     "legendFormat": "Fetched - {{datname}}"
    }
   ]
  }
 ]
}