apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-exporter
  template:
    metadata:
      labels:
        app: postgres-exporter
    spec:
      containers:
        - name: exporter
          image: prometheuscommunity/postgres-exporter
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://myuser:mypassword@postgres.postgres-database.svc.cluster.local:5432/mydb?sslmode=disable"
          ports:
            - containerPort: 9187
